image: 
  name: docksal/cli
  username: $DOCKER_HUB_USERNAME
  password: $DOCKER_HUB_PASSWORD
  email: $DOCKER_HUB_EMAIL
  
pipelines:
  default:
    - step:
        script:
          - cd docroot/themes/ci_xy
          - gulp