image: 
  name: alfredonz/alfredo
  username: $DOCKER_HUB_USERNAME
  password: $DOCKER_HUB_PASSWORD
  email: $DOCKER_HUB_EMAIL
  
pipelines:
  default:
    - step:
        script:
          - ls
          - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD