image: node:6.9.4
pipelines:
  default:
    - step:
        script:
          - npm install
                    - npm install -g bower
                    - bower install --allow-root
                    - npm install -g gulp
                    - gulp